url: https://limerobot.github.io
baseurl: ""

# Site settings
title: Lime Robot Software
email: limerobotsoftware@gmail.com
description: "Lime Robot - custom software development"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5d8749
  secondary: 6d935b  
  secondary-dark: 333

# Team names, titles and social links
#people:
#- name: Kay Garland
#  pic: 1
#  position: Lead Designer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/lime_robot
  - title: facebook
    url: https://www.facebook.com/LimeRobot
  - title: google-plus
    url: https://plus.google.com/104783130329480509358
  - title: bitbucket 
    url: https://bitbucket.org/limerobot
  - title: github
    url: https://github.com/limerobot

# Postal address (add as many lines as necessary)
address:
  - line: Mason, OH 45040

# Build settings
markdown: kramdown
permalink: pretty
